Tooltip
js-tasks-ru/htmlcss-20230227_vadim700 pull request #11
Opened 2023-03-14 18:10 UTC by Vadim700

added tooltip

2023-03-14 18:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 01:46 UTC, GSemikozov requested changes

2023-03-15 01:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные стили удаляем (если нужен отступ на пустой странице - прямо там его и надо добавить, можно через тег style)

2023-03-15 01:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +	left: -220%;
ширина как триггера, так и бабла всегда может быть разной, так что - `left: 50%; transform: translateX(-50%)`

2023-03-15 13:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 13:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-15 13:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-15 14:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 10:50 UTC, GSemikozov requested changes

2023-03-16 14:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 15:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 15:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 15:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 15:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-16 15:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 15:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 21:31 UTC, GSemikozov approved these changes

2023-03-16 21:31 UTC, merged