Input
js-tasks-ru/htmlcss-20230227_vadim700 pull request #22
Opened 2023-03-22 19:23 UTC by Vadim700

2023-03-22 20:49 UTC, GSemikozov requested changes

2023-03-22 20:49 UTC, GSemikozov commented on components/formgroup/formgroup.css
> +.formgroup_error .formgroup__wrapper input {
.formgroup_error .formgroup__input {}

2023-03-22 20:49 UTC, GSemikozov commented on components/input/input.css
> +	cursor: not-allowed;
pointer-events: none

2023-03-23 15:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 07:59 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-24 15:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-26 19:51 UTC, GSemikozov approved these changes

2023-03-26 19:51 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-26 19:59 UTC, GSemikozov approved these changes

2023-03-26 20:00 UTC, merged