Macro preview
js-tasks-ru/htmlcss-20230227_vadim700 pull request #23
Opened 2023-03-28 19:28 UTC by Vadim700

cards-preview, page-tooltip, tabs for tooltip

2023-03-28 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-29 09:29 UTC, GSemikozov requested changes

2023-03-29 09:29 UTC, GSemikozov commented on components/card/card.css
> +	grid-template: repeat(3, auto)/repeat(2, auto);
точно ли надо так жестко определять темплейт для этого элемента? если да, то класс какой-то более смысловой нужен

2023-03-29 09:29 UTC, GSemikozov commented on components/card/card.css
> +.card__content_modal {
модификаторы под каждый встраиваемый компонент делать не надо - должен быть универсальный принцип встраивания всех компонентов. Если что-то специфические для встраиваемого компонента - то на уровне этого компонента модификатор

2023-03-29 09:29 UTC, GSemikozov commented on components/formgroup/formgroup.css
> +.formgroup__label_preview {
.formgroup__preview .formgroup__label

2023-03-29 09:29 UTC, GSemikozov commented on components/tabs/tabs.css
> +	display: none;
такой способ скрытия не позволить переключать состояние через клавиатуру

2023-03-29 09:29 UTC, GSemikozov commented on components/tabs/tabs.css
> +	width: 120%;
точно ли это надо?

2023-03-29 17:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-30 10:45 UTC, GSemikozov requested changes

2023-03-30 10:45 UTC, GSemikozov commented on assets/css/main.css
> +    padding: 0 calc(17px - (100vw - 100%)) 0 0;
какой-то лишний паддинг - удалим)

2023-03-30 10:45 UTC, GSemikozov commented on components/card/card.css
> +	grid-template: repeat(3, auto)/repeat(2, auto);
тут не получил ответа)

2023-03-30 10:45 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__input_tab1:checked~.tabs__content_tab1,
_tab1 - это оооооочень неинформативное имя класс-модификатора, непонятно за что он отвечает, ЧТО модифицирует. Лучше больше букв, но понятнее)

2023-03-30 16:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-31 16:53 UTC, GSemikozov requested changes

2023-04-01 11:01 UTC, Vadim700 commented on components/tabs/tabs.css
> +	width: 120%;
Изначально показалось что подчеркивание не полностью заполняет блок с текстом. Сделал как по дизайну.

2023-04-04 19:43 UTC, GSemikozov approved these changes

2023-04-04 19:43 UTC, GSemikozov commented on components/card/card.css
> +	grid-template: repeat(3, auto)/repeat(2, auto);
до сих пор

2023-04-04 19:43 UTC, merged